[package]
name = "spaceapi-server"
version = "0.2.1-dev"
documentation = "https://coredump-ch.github.io/spaceapi-server-rs/"
repository = "https://github.com/coredump-ch/spaceapi-server-rs"
license = "MIT OR Apache-2.0"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
    "Stefan Schindler <stefan@estada.ch>",
]
description = "A library that allows you to easily implement a Space API server."
readme = "README.md"
keywords = ["spaceapi", "hackerspaces", "status", "api", "server"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
    "AUTHORS.md",
]

[dependencies]
r2d2 = "^0.7"
r2d2_redis = "^0.3.1"
redis = "^0.5"
rustc-serialize = "^0.3"
iron = "^0.3"
hyper = "^0.8"
log = "^0.3"
urlencoded = "^0.3"
router = "^0.1"
error-type = "^0.1"
spaceapi = "^0.1"

[dev-dependencies]
env_logger = "^0.3"
