[package]
name = "spaceapi-server"
version = "0.3.1"
documentation = "https://coredump-ch.github.io/spaceapi-server-rs/"
repository = "https://github.com/coredump-ch/spaceapi-server-rs"
license = "MIT OR Apache-2.0"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
    "Stefan Schindler <stefan@estada.ch>",
]
description = "A library that allows you to easily implement a Space API server."
readme = "README.md"
keywords = ["spaceapi", "hackerspaces", "status", "api", "server"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "CHANGELOG.md",
    "AUTHORS.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[badges]
travis-ci = { repository = "coredump-ch/spaceapi-server-rs" }

[dependencies]
r2d2 = "^0.7"
r2d2_redis = "^0.4"
redis = "^0.6"
rustc-serialize = "^0.3"
iron = "^0.4"
hyper = "^0.9"
log = "^0.3"
urlencoded = "^0.4"
router = "^0.2"
error-type = "^0.1"
serde_json = "^0.8"
spaceapi = "^0.4"
clippy = {version = "^0.0.87", optional = true}

[features]
unstable = ["clippy"]

[dev-dependencies]
env_logger = "^0.3"
